"""Adding filtered jobs table.

Revision ID: b974d777716d
Revises: 9f5b3ae34e8c
Create Date: 2026-03-24 15:06:26.269767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b974d777716d"
down_revision: Union[str, Sequence[str], None] = "9f5b3ae34e8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filtered_jobs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("applylink", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("cover_letter", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("easy_apply", sa.Boolean(), nullable=False),
        sa.Column("ai_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pending_jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("easy_apply", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pending_jobs", schema=None) as batch_op:
        batch_op.drop_column("easy_apply")

    op.drop_table("filtered_jobs")
    # ### end Alembic commands ###
